## 1) IMPORTING DATA (CLEANED)

In [35]:
import numpy as np 
import pandas as pd

In [36]:
df=pd.read_csv("../data/superstore_data_cleaned.csv",encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Delivery Time,Year of order,Month of order,Weekday of order
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3,2016,11,1
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3,2016,11,1
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4,2016,6,6
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7,2015,10,6
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7,2015,10,6

## 2) Analysing Attributes

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID            9994 non-null   int64
 1   Order ID          9994 non-null   str
 2   Order Date        9994 non-null   str
 3   Ship Date         9994 non-null   str
 4   Ship Mode         9994 non-null   str
 5   Customer ID       9994 non-null   str
 6   Customer Name     9994 non-null   str
 7   Segment           9994 non-null   str
 8   Country           9994 non-null   str
 9   City              9994 non-null   str
 10  State             9994 non-null   str
 11  Postal Code       9994 non-null   int64
 12  Region            9994 non-null   str
 13  Product ID        9994 non-null   str
 14  Category          9994 non-null   str
 15  Sub-Category      9994 non-null   str
 16  Product Name      9994 non-null   str
 17  Sales             9994 non-null   float64
 18  Quantity          9994 non-null   int64
 19  Discount          9994 non-null   float64
 20  Profit            9994 non-null   float64
 21  Delivery Time     9994 non-null   int64
 22  Year of order     9994 non-null   int64
 23  Month of order    9994 non-null   int64
 24  Weekday of order  9994 non-null   int64
dtypes: float64(3), int64(7), str(15)
memory usage: 1.9 MB

In [38]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Delivery Time', 'Year of order', 'Month of order', 'Weekday of order'],
      dtype='str')

## 3) Removing unwanted columns for model training

In [39]:
# dont need unique /identifier attributes like-
dropped=[]
# Row id, Order ID, customer id, customer name, product id, product name

In [40]:
arr1=['Row ID', 'Order ID','Customer ID', 'Customer Name','Product ID','Product Name']
dropped.extend(arr1)
df=df.drop(columns=arr1)

In [41]:
df.head()

,Order Date,Ship Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Delivery Time,Year of order,Month of order,Weekday of order
0,2016-11-08,2016-11-11,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,3,2016,11,1
1,2016-11-08,2016-11-11,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,3,2016,11,1
2,2016-06-12,2016-06-16,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,4,2016,6,6
3,2015-10-11,2015-10-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,7,2015,10,6
4,2015-10-11,2015-10-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,7,2015,10,6

In [42]:
df['Country'].unique()

<StringArray>
['United States']
Length: 1, dtype: str

In [43]:
# no value in ML model, also we have state and city- so no need for postal code(zipcode)

In [44]:
arr2=['Country','Postal Code']
dropped.extend(arr2)
df=df.drop(columns=arr2)

In [45]:
# we can remove columns Order Date and Ship date
# we've already extracted the year, month, weekday and time to ship

In [46]:
arr3=['Order Date','Ship Date']
dropped.extend(arr3)
df=df.drop(columns=arr3)

In [47]:
df.columns

Index(['Ship Mode', 'Segment', 'City', 'State', 'Region', 'Category',
       'Sub-Category', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Delivery Time', 'Year of order', 'Month of order', 'Weekday of order'],
      dtype='str')

In [48]:
dropped

['Row ID',
 'Order ID',
 'Customer ID',
 'Customer Name',
 'Product ID',
 'Product Name',
 'Country',
 'Postal Code',
 'Order Date',
 'Ship Date']

## 4) Encode categorical columns

In [49]:
df['Ship Mode'].unique()

<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

In [50]:
# segment has 3 categories
# ship mode has 4 categories
# state has 49 categories
# region has 4 categories-can be dropped as state already considered
# category has 3 categories
# sub-category has 17 categories

In [51]:
encoded = ['Ship Mode', 'Segment', 'State', 'Category', 'Sub-Category']
df = pd.get_dummies(df, columns=encoded, drop_first=True)

In [52]:
# removing city as state gives enough variations
# 500 unique values can cause overfit

In [53]:
df=df.drop(columns=['City','Region'])
dropped.extend(['City','Region'])

In [54]:
df.head()

,Sales,Quantity,Discount,Profit,Delivery Time,Year of order,Month of order,Weekday of order,Ship Mode_Same Day,Ship Mode_Second Class,...,Sub-Category_Envelopes,Sub-Category_Fasteners,Sub-Category_Furnishings,Sub-Category_Labels,Sub-Category_Machines,Sub-Category_Paper,Sub-Category_Phones,Sub-Category_Storage,Sub-Category_Supplies,Sub-Category_Tables
0,261.9600,2,0.00,41.9136,3,2016,11,1,False,True,...,False,False,False,False,False,False,False,False,False,False
1,731.9400,3,0.00,219.5820,3,2016,11,1,False,True,...,False,False,False,False,False,False,False,False,False,False
2,14.6200,2,0.00,6.8714,4,2016,6,6,False,True,...,False,False,False,True,False,False,False,False,False,False
3,957.5775,5,0.45,-383.0310,7,2015,10,6,False,False,...,False,False,False,False,False,False,False,False,False,True
4,22.3680,2,0.20,2.5164,7,2015,10,6,False,False,...,False,False,False,False,False,False,False,True,False,False

In [56]:
df.columns

Index(['Sales', 'Quantity', 'Discount', 'Profit', 'Delivery Time',
       'Year of order', 'Month of order', 'Weekday of order',
       'Ship Mode_Same Day', 'Ship Mode_Second Class',
       'Ship Mode_Standard Class', 'Segment_Corporate', 'Segment_Home Office',
       'State_Arizona', 'State_Arkansas', 'State_California', 'State_Colorado',
       'State_Connecticut', 'State_Delaware', 'State_District of Columbia',
       'State_Florida', 'State_Georgia', 'State_Idaho', 'State_Illinois',
       'State_Indiana', 'State_Iowa', 'State_Kansas', 'State_Kentucky',
       'State_Louisiana', 'State_Maine', 'State_Maryland',
       'State_Massachusetts', 'State_Michigan', 'State_Minnesota',
       'State_Mississippi', 'State_Missouri', 'State_Montana',
       'State_Nebraska', 'State_Nevada', 'State_New Hampshire',
       'State_New Jersey', 'State_New Mexico', 'State_New York',
       'State_North Carolina', 'State_North Dakota', 'State_Ohio',
       'State_Oklahoma', 'State_Oregon', 'State_Pennsylvania',
       'State_Rhode Island', 'State_South Carolina', 'State_South Dakota',
       'State_Tennessee', 'State_Texas', 'State_Utah', 'State_Vermont',
       'State_Virginia', 'State_Washington', 'State_West Virginia',
       'State_Wisconsin', 'State_Wyoming', 'Category_Office Supplies',
       'Category_Technology', 'Sub-Category_Appliances', 'Sub-Category_Art',
       'Sub-Category_Binders', 'Sub-Category_Bookcases', 'Sub-Category_Chairs',
       'Sub-Category_Copiers', 'Sub-Category_Envelopes',
       'Sub-Category_Fasteners', 'Sub-Category_Furnishings',
       'Sub-Category_Labels', 'Sub-Category_Machines', 'Sub-Category_Paper',
       'Sub-Category_Phones', 'Sub-Category_Storage', 'Sub-Category_Supplies',
       'Sub-Category_Tables'],
      dtype='str')

## 5) Final Summary

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 79 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Sales                       9994 non-null   float64
 1   Quantity                    9994 non-null   int64
 2   Discount                    9994 non-null   float64
 3   Profit                      9994 non-null   float64
 4   Delivery Time               9994 non-null   int64
 5   Year of order               9994 non-null   int64
 6   Month of order              9994 non-null   int64
 7   Weekday of order            9994 non-null   int64
 8   Ship Mode_Same Day          9994 non-null   bool
 9   Ship Mode_Second Class      9994 non-null   bool
 10  Ship Mode_Standard Class    9994 non-null   bool
 11  Segment_Corporate           9994 non-null   bool
 12  Segment_Home Office         9994 non-null   bool
 13  State_Arizona               9994 non-null   bool
 14  State_Arkansas              9994 non-null   bool
 15  State_California            9994 non-null   bool
 16  State_Colorado              9994 non-null   bool
 17  State_Connecticut           9994 non-null   bool
 18  State_Delaware              9994 non-null   bool
 19  State_District of Columbia  9994 non-null   bool
 20  State_Florida               9994 non-null   bool
 21  State_Georgia               9994 non-null   bool
 22  State_Idaho                 9994 non-null   bool
 23  State_Illinois              9994 non-null   bool
 24  State_Indiana               9994 non-null   bool
 25  State_Iowa                  9994 non-null   bool
 26  State_Kansas                9994 non-null   bool
 27  State_Kentucky              9994 non-null   bool
 28  State_Louisiana             9994 non-null   bool
 29  State_Maine                 9994 non-null   bool
 30  State_Maryland              9994 non-null   bool
 31  State_Massachusetts         9994 non-null   bool
 32  State_Michigan              9994 non-null   bool
 33  State_Minnesota             9994 non-null   bool
 34  State_Mississippi           9994 non-null   bool
 35  State_Missouri              9994 non-null   bool
 36  State_Montana               9994 non-null   bool
 37  State_Nebraska              9994 non-null   bool
 38  State_Nevada                9994 non-null   bool
 39  State_New Hampshire         9994 non-null   bool
 40  State_New Jersey            9994 non-null   bool
 41  State_New Mexico            9994 non-null   bool
 42  State_New York              9994 non-null   bool
 43  State_North Carolina        9994 non-null   bool
 44  State_North Dakota          9994 non-null   bool
 45  State_Ohio                  9994 non-null   bool
 46  State_Oklahoma              9994 non-null   bool
 47  State_Oregon                9994 non-null   bool
 48  State_Pennsylvania          9994 non-null   bool
 49  State_Rhode Island          9994 non-null   bool
 50  State_South Carolina        9994 non-null   bool
 51  State_South Dakota          9994 non-null   bool
 52  State_Tennessee             9994 non-null   bool
 53  State_Texas                 9994 non-null   bool
 54  State_Utah                  9994 non-null   bool
 55  State_Vermont               9994 non-null   bool
 56  State_Virginia              9994 non-null   bool
 57  State_Washington            9994 non-null   bool
 58  State_West Virginia         9994 non-null   bool
 59  State_Wisconsin             9994 non-null   bool
 60  State_Wyoming               9994 non-null   bool
 61  Category_Office Supplies    9994 non-null   bool
 62  Category_Technology         9994 non-null   bool
 63  Sub-Category_Appliances     9994 non-null   bool
 64  Sub-Category_Art            9994 non-null   bool
 65  Sub-Category_Binders        9994 non-null   bool
 66  Sub-Category_Bookcases      9994 non-null   bool
 67  Sub-Category_Chairs         9994 non-null   bool
 68  Sub-Category_Copiers        9994 non-null   bool
 69  Sub-Category_Envelopes      9994 non-null   bool
 70  Sub-Category_Fasteners      9994 non-null   bool
 71  Sub-Category_Furnishings    9994 non-null   bool
 72  Sub-Category_Labels         9994 non-null   bool
 73  Sub-Category_Machines       9994 non-null   bool
 74  Sub-Category_Paper          9994 non-null   bool
 75  Sub-Category_Phones         9994 non-null   bool
 76  Sub-Category_Storage        9994 non-null   bool
 77  Sub-Category_Supplies       9994 non-null   bool
 78  Sub-Category_Tables         9994 non-null   bool
dtypes: bool(71), float64(3), int64(5)
memory usage: 1.3 MB

In [59]:
#Dropped Columns
dropped

['Row ID',
 'Order ID',
 'Customer ID',
 'Customer Name',
 'Product ID',
 'Product Name',
 'Country',
 'Postal Code',
 'Order Date',
 'Ship Date',
 'City',
 'Region']

In [60]:
#encoded columns
encoded

['Ship Mode', 'Segment', 'State', 'Category', 'Sub-Category']

In [64]:
df.isnull().sum().sum().item()

0

In [65]:
df.duplicated().sum().item()

1

In [67]:
df[df.duplicated(keep=False)]
# true duplicate- most likely because of removing order id and product id

,Sales,Quantity,Discount,Profit,Delivery Time,Year of order,Month of order,Weekday of order,Ship Mode_Same Day,Ship Mode_Second Class,...,Sub-Category_Envelopes,Sub-Category_Fasteners,Sub-Category_Furnishings,Sub-Category_Labels,Sub-Category_Machines,Sub-Category_Paper,Sub-Category_Phones,Sub-Category_Storage,Sub-Category_Supplies,Sub-Category_Tables
3405,281.372,2,0.3,-12.0588,4,2014,4,2,False,False,...,False,False,False,False,False,False,False,False,False,False
3406,281.372,2,0.3,-12.0588,4,2014,4,2,False,False,...,False,False,False,False,False,False,False,False,False,False

In [68]:
df.drop_duplicates(inplace=True)

In [69]:
df.to_csv("../data/Superstore_prepared.csv", index=False)