## 1) Import Data

In [150]:
import numpy as np 
import pandas as pd

In [151]:
df=pd.read_csv("../data/superstore_data.csv",encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

### Summary of data

In [152]:
#checking info of all columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [153]:
#checking some basic descriptive stats
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [154]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

## 2) Check Duplicates

In [155]:
df.duplicated().sum().item()

0

In [156]:
#This shows that the dataframe has no duplicate values

## 3) Check NaN values

In [157]:
df.isna().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [158]:
# This shows the dataset has no null values present

## 4)Change types of Shipment Date and Order Date

In [159]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [160]:
df["Order Date"].head()

0   2016-11-08
1   2016-11-08
2   2016-06-12
3   2015-10-11
4   2015-10-11
Name: Order Date, dtype: datetime64[us]

## 5)Creating new columns-

### delivery time , year of order , month of order , day of order

In [161]:
# This column shows the number of days for delivery
df["Delivery Time"]=(df["Ship Date"]-df["Order Date"]).dt.days

In [162]:
df["Delivery Time"].head()

0    3
1    3
2    4
3    7
4    7
Name: Delivery Time, dtype: int64

In [163]:
df["Year of order"]=df["Order Date"].dt.year
df["Month of order"]=df["Order Date"].dt.month
df["Weekday of order"]=df["Order Date"].dt.weekday

In [164]:
# This column shows the year of order
df["Year of order"].head()

0    2016
1    2016
2    2016
3    2015
4    2015
Name: Year of order, dtype: int32

In [165]:
# This column shows the month number of order
df["Month of order"].head()

0    11
1    11
2     6
3    10
4    10
Name: Month of order, dtype: int32

In [166]:
# This column shows the day of week(in number) of order
df["Weekday of order"].tail()

9989    1
9990    6
9991    6
9992    6
9993    3
Name: Weekday of order, dtype: int32

In [167]:
df["Order Date"] = df["Order Date"].dt.strftime("%Y-%m-%d")
df["Ship Date"] = df["Ship Date"].dt.strftime("%Y-%m-%d")

## 6)Check for inconsistencies

In [168]:
for col in ["Ship Mode","Segment","Category","Sub-Category","Region"]:
    print(col)
    print(df[col].unique())
    print()

Ship Mode
<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

Segment
<StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

Category
<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

Sub-Category
<StringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

Region
<StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

## 7)Check for Outliers

In [169]:
df[["Sales","Profit","Discount","Quantity"]].describe()

              Sales       Profit     Discount     Quantity
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001    28.656896     0.156203     3.789574
std      623.245101   234.260108     0.206452     2.225110
min        0.444000 -6599.978000     0.000000     1.000000
25%       17.280000     1.728750     0.000000     2.000000
50%       54.490000     8.666500     0.200000     3.000000
75%      209.940000    29.364000     0.200000     5.000000
max    22638.480000  8399.976000     0.800000    14.000000

## 8)Final Summary

In [170]:
# Missing values
print(df.isnull().sum())

Row ID              0
Order ID            0
Order Date          0
Ship Date           0
Ship Mode           0
Customer ID         0
Customer Name       0
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Product ID          0
Category            0
Sub-Category        0
Product Name        0
Sales               0
Quantity            0
Discount            0
Profit              0
Delivery Time       0
Year of order       0
Month of order      0
Weekday of order    0
dtype: int64

In [171]:
# Duplicates
print(df.duplicated().sum())

0

In [172]:
# Numeric summary
print(df[["Sales","Profit","Discount","Quantity","Delivery Time"]].describe())

              Sales       Profit     Discount     Quantity  Delivery Time
count   9994.000000  9994.000000  9994.000000  9994.000000    9994.000000
mean     229.858001    28.656896     0.156203     3.789574       3.958175
std      623.245101   234.260108     0.206452     2.225110       1.747567
min        0.444000 -6599.978000     0.000000     1.000000       0.000000
25%       17.280000     1.728750     0.000000     2.000000       3.000000
50%       54.490000     8.666500     0.200000     3.000000       4.000000
75%      209.940000    29.364000     0.200000     5.000000       5.000000
max    22638.480000  8399.976000     0.800000    14.000000       7.000000

In [173]:
# Dataset shape
print(df.shape)

(9994, 25)

In [174]:
# Final data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID            9994 non-null   int64
 1   Order ID          9994 non-null   str
 2   Order Date        9994 non-null   str
 3   Ship Date         9994 non-null   str
 4   Ship Mode         9994 non-null   str
 5   Customer ID       9994 non-null   str
 6   Customer Name     9994 non-null   str
 7   Segment           9994 non-null   str
 8   Country           9994 non-null   str
 9   City              9994 non-null   str
 10  State             9994 non-null   str
 11  Postal Code       9994 non-null   int64
 12  Region            9994 non-null   str
 13  Product ID        9994 non-null   str
 14  Category          9994 non-null   str
 15  Sub-Category      9994 non-null   str
 16  Product Name      9994 non-null   str
 17  Sales             9994 non-null   float64
 18  Quantity          9994 non-null   int64
 19  Discount          9994 non-null   float64
 20  Profit            9994 non-null   float64
 21  Delivery Time     9994 non-null   int64
 22  Year of order     9994 non-null   int32
 23  Month of order    9994 non-null   int32
 24  Weekday of order  9994 non-null   int32
dtypes: float64(3), int32(3), int64(4), str(15)
memory usage: 1.8 MB

## 9)Final Save to CSV format

In [175]:
df.to_csv("../data/superstore_data_cleaned.csv", index=False)